
This sections documents the various capabilities a production node may have.
The main classes will all refer to the sub-sections found here.

[comment %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%]

[include c_cap_altview.inc]
[include c_cap_antiflicker.inc]
[include c_cap_cropping.inc]
[include c_cap_framesync.inc]
[include c_cap_handfov.inc]
[include c_cap_mirror.inc]
[include c_cap_pose.inc]
[include c_cap_skeleton.inc]
[include c_cap_general_int.inc]

