[def [arg gesture]]
The name of the gesture which was recognized

[def [arg idPosition]]
The position where the gesture was recognized. This is a 3-element
list of floating point values containing the [term {real world}]
x-, y-, and z-coordinates of the position, in this order.

[def [arg endPosition]]
The position of the hand at the end of the gesture. This is a
3-element list of floating point values containing the
[term {real world}] x-, y-, and z-coordinates of the position, in this
order.
