The detail dictionary of this event contains:

[list_begin definitions]
[def [arg user]]
The numerical id of the user the event was generated for.

[def [arg joint]]
The name of the joint the event was generated for.

[def [arg position]]
The current position of the joint. This is a 3-element list of
floating point values containing the [term {real world}] x-, y-, and
z-coordinates of the position, in this order.

[list_end]
