
[subsection Crimp]

The image processing package
[uri http://chiselapp.com/user/andreas_kupries/repository/crimp/home CRIMP]
is required to build and use KineTcl.

[para] Note that the currently released version of crimp does not have
       all the operations used by KineTcl. Please make sure to use at
       least commit [lb]795374375f[rb], or later.

[para]

The link for crimp goes to its official website which explains how to
get the sources and how to install them.
