
[subsection CriTcl]

The tool [uri http://jcw.github.com/critcl critcl] is required to
build KineTcl, either as an application found in the PATH, or as a Tcl
package available to the [cmd tclsh] used to run KineTcl's
[sectref {Build & Installation}] process.

[para] The not-yet-released version 3.1 is required, or higher, and
       the utility package [package critcl::class]. This is currently
       only available on the [const dev31] branch of the critcl
       repository at github linked to in the previous paragraph.

[para] Please make sure to use at least commit [lb]fe814d4977[rb], or
later.

[para]

The link for critcl goes to its official website which explains how to
get the sources, and how to install them. Note that the starkit at the
site is [emph not] useable, as it provides only critcl 3, nor the
utility package we need.
