
[subsection CriTcl]

The tool [uri http://jcw.github.com/critcl critcl] is required to
build KineTcl, either as an application found in the PATH, or as a Tcl
package available to the [cmd tclsh] used to run KineTcl's
[sectref {Build & Installation}] process.

[para] Version 3.1 is required, or higher, and the utility package
       [package critcl::class]. This is currently only available on
       the [const dev31] branch of the critcl repository at github
       linked to in the previous paragraph.

[para]

The link for critcl goes it its official website which explains how to
get its sources. The starkit at the site is [emph not] useable, as it
provides only critcl 3, nor the utility package we need.

[para]

When not using a starkit as is required here for the moment, you have
to get and install the sources per the instructions at the site,
i.e. [uri http://jcw.github.com/critcl].
